spring:
      datasource:
            url: jdbc:postgresql://localhost:5432/db1
            username: postgres
            password: 1234
      jpa:
            generate-ddl: true
            hibernate:
                  ddl-auto: update