spring:
      datasource1:
            url: jdbc:postgresql://localhost:5432/db1
            username: postgres
            password: 1234
      datasource2:
            url: jdbc:postgresql://localhost:5432/db2
            username: postgres
            password: 1234
      datasource3:
            url: jdbc:postgresql://localhost:5432/db3
            username: postgres
            password: 1234
      main:
            allow-bean-definition-overriding: true






