spring:
      datasource1:
            url: jdbc:postgresql://localhost:5432/db1
            username: postgres
            password: 1234


#            schema: classpath:/customer-schema.sql
#            data: classpath:/customer-data.sql
      datasource2:
            url: jdbc:postgresql://localhost:5432/db2
            username: postgres
            password: 1234






